apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
  labels:
    app: enrollment-service
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app: enrollment-service